export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const REMOVE_ALL_PRODUCT_FROM_CART = "REMOVE_ALL_PRODUCT_FROM_CART"
export const INCREASE_THE_QUANTITY = "INCREASE_THE_QUANTITY";
export const LACK_THE_QUANTITY = "LACK_THE_QUANTITY";